<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Relatorio extends Model
{
    protected $fillable =[
        'idCliente',
        'data',
        'atendimento',
        'tipo',
        'horimetro',
        'kwh',
        'colmeia',
        'aguaRadiador',
        'obsAguaRadiador',
        'aditivoArrefecedor',
        'obsAditivoArrefecedor',
        'oleoCarter',
        'obsOleoCarter',
        'mangotes',
        'obsMangotes',
        'preAquecimento',
        'obsPreAquecimento',
        'limpezaSensorRotacao',
        'obslimpezaSensorRotacao',
        'vazamentoJuntas',
        'obsVazamentoJuntas',
        'nivelCombustivel',
        'obsnivelCombustivel',
        'filtroDeAr',
        'obsFiltroDeAr',
        'correias',
        'obsCorreias',
        'gradesTampas',
        'obsGradesTampas',
        'baterias',
        'reguladorDeTensao',
        'obsReguladorDeTensao',
        'bornes',
        'obsBornes',
        'tensaoContinuaCarregador',
        'ampereCarregador',
        'tensaoContinuaAlternador',
        'ampereAlternador',
        'f1F2',
        'obsF1F2',
        'f2F3',
        'obsF2F3',
        'f1f3',
        'obsF1f3',
        'frequencia',
        'pressaoOleo',
        'temperaturaMotor',
        'vazamentoConexoes',
        'obsVazamentoConexoes',
        'ruidosAnormais',
        'obsRuidosAnormais',
        'densidadeFumaca',
        'obsDensidadeFumaca',
        'limpezaSuperficial',
        'obsLimpezaSuperficial',
        'testeEmCarga',
        'obsTesteEmCarga',
        'estadoGeralEquipamento',
        'obsGerais',
        'fotoMotor',
        'fotoCabinado',
        'fotoGeral',
        'feitoPor',
    ];
    use HasFactory;
}
